### ISSUE TITLE
Jenkins won't install updated plugins pinned by this package

### ISSUE THREAD

**Issue by dothebart** [mesosphere/dcos-jenkins-service#105] opened 2016-09-23 08:50 UTC
It seems the mesosphere jenkins package nails the plugins to specific versions. The plugin manager allways tells 'new version available' but downloading fails
I've tried at the example of the ant plugin, which is pinned to 1.3, but 1.4 is well available

This is what I've learned in #jenkins on freenode IRC:

20:06 @danielbeck: dothebart after you have downloaded an update and before restarting Jenkins?
20:07  dothebart: after the restart
20:08 @danielbeck: dothebart which doesn't tell us whether the download/install failed, or whether it was reset on restart.
20:08  dothebart: ok, after the download and before the restart its: Implementation-Version: 1.4
20:10 @danielbeck: wtf is this shit https://github.com/mesosphere/jenkins-dcos/blob/f892ce5cd322b14c21e1c6568c7cde3af3cb3c64/pom.xml
20:11 @danielbeck: dothebart It's a problem with your distribution of Jenkins, which isn't the ofifcial one
20:11  dothebart: ok, so its nailed to these versions?
20:12 @danielbeck: I think so. We used to bundle plugins in Jenkins but no longer do so -- I think while it's technically still possible to bundle in custom Jenkinses, we dropped some of the supporting infrastructure like plugin pinning that made it work 
(https://wiki.jenkins-ci.org/display/JENKINS/Pinned+Plugins)
20:13  dothebart: ok, I'll cx-paste this to that channel if its ok for you?
20:14 @danielbeck: sure, with the disclaimer that I haven't looked at how much of that functionality still exists, so could well be wrong -- but it looks like a likely explanation to me of DCOS Jenkins bundles plugins
20:14 @danielbeck: s/of/if
20:14  dothebart: okies, thanks.
20:15  dothebart: this used to be different last week... so I guess one of both changed the behaviour... we'll find out.
20:15 @danielbeck: that... is a very opinionated list of plugins O_O

it used to be working with the setup I did three weeks ago on DC/OS 1.7 [tm]
but now I'm all out of luck.

20:19  dothebart: danielbeck: the way jenkins works with such lists is a bit... counterintuitive?
20:20 @danielbeck: dothebart what lists?
20:20  dothebart: it could visiualise / log that its pinned to a specific version, and won't upgrade 
20:21 @danielbeck: dothebart that's not how it works (or worked). Pinning never prohibited you from doing something, like upgrading, but if the plugin was bundled it was pinned to prevent the automatic downgrade on restart
20:22  dothebart: since I was looking at the log, and such a message would have saved me some hours
20:22 @danielbeck: dothebart So my guess is that we ripped out the code that pinned a plugin on update since Jenkins no longer bundles any plugins this way, and now it always gets overwritten on restart

**Comment by ssk2** [comment] 2016-09-23 12:41
Hey @dothebart: investigating! Are you using the latest version of the package? 2.0.1-2.7.4?

**Comment by dothebart** [comment] 2016-09-23 12:55
the mesosphere desc: 

    "container": {
    "docker": {
      "image": "mesosphere/jenkins:2.0.1-2.7.4",
      "forcePullImage": false,
      "privileged": false,
      "network": "HOST"
    },

so I guess - yes?

**Comment by dothebart** [comment] 2016-09-23 12:57
Most probably I know why it "worked" with my last installation: 
 - it installed 2.7.3 via the DC/OS scripts
- I was prompted that there is a 2.7.4 available in the jenkins webui, which I clicked to download & install
after that the plugins probably started to work - I got blue ocean plugins that started to become usefull.

**Comment by colin-msphere** [comment] 2016-09-23 17:34
Confirmed this behavior. Upgrading a bundled plugin will revert back to the bundled version.

**Comment by joerg84** [comment] 2016-09-30 12:40
@ssk2 Do we have an update here by any chance?

**Comment by dothebart** [comment] 2016-10-04 10:20
Since much of the pipeline & groovy stuff which one would want to use to distribute build jobs across DC/OS nodes is evolving pretty quickly, this makes the docker container as its now almost useless for production. One workaround could be for now to follow these updates and provide an updated version of the container with the current module versions - and follow upstream with subsequent updates to this container.

**Comment by garethrowlands** [comment] 2016-10-04 16:00
How about starting from the cloudbees Jenkins docker image and following their instructions for installing plugins in a docker container?

* https://github.com/jenkinsci/docker
* https://github.com/jenkinsci/docker/blob/master/install-plugins.sh

How important is nginx?

**Comment by ssk2** [comment] 2016-10-04 16:07
That's a good idea @garethrowlands! Will look into it. We need nginx to work behind DC/OS's reverse proxy (although the proxy configuration will hopefully be amended in the next release of DC/OS to allow us to remove nginx).

**Comment by dothebart** [comment] 2016-10-05 14:15
Ok, right now the Jenkins team has released a new jenkins version. So now one can get rid of this problem by just upgrading jenkins. Please don't publish a new version of this docker until this problem is solved.

**Comment by ssk2** [comment] 2016-10-05 15:34
@dothebart: what problem are you referring to?

**Comment by dothebart** [comment] 2016-10-06 07:34
the WAR this package ships will forcibly downgrade plugins this package brings after any attempt to upgrade them. Once it replaces itself with an upstream update (as happened yesterday) this missbehaviour goes away - one can install updates and live happy.

**Comment by ssk2** [comment] 2016-10-06 15:19
Ah, perfect! I will try this out and release a new version if that works.

**Comment by PascalPflaum** [comment] 2016-10-19 14:25
Hi.

I run in the same problem and I would be happy having the possibility to update the plugins in my dcos jenkins. Can you give me an update on this?

Any good workaround?
Inherit the mesosphere/jenkins:2.0.1-2.7.4 container image and overwrite the whole pom.xml.

**Comment by LinkMJB** [comment] 2016-11-28 20:56
Any chance this is being worked @ssk2? From what I can tell, it should just be a simple one-line change to the Dockerfile to `wget http://mirrors.jenkins.io/war-stable/2.19.3/jenkins.war`, rather than providing a bundled war in the local build environment for the Docker image.

**Comment by colin-msphere** [comment] 2016-11-28 22:10
The current approach, which is a bundled `war` with included plugins, allows users in an offline scenario to install a Jenkins instance with some plugins available immediately.

We are investigating the docker approach as recommended by the Jenkins team (using `jenkinsci/docker` and `install-plugins.sh`).

**Comment by LinkMJB** [comment] 2016-11-28 22:33
Wouldn't it make better sense to make that available as an offline branch/version, rather than making that the default/assumption for the master branch? Anyone upgrading to this version are going to be badly broken, and have all of their plugins frozen until they upgrade their entire Jenkins DC/OS package, fork, or decouple the Docker image from what was delivered with the Jenkins DC/OS package.

**Comment by CarltonHenderson** [comment] 2016-12-30 23:20
I'm continuing to have this issue (can't update any of the bundled plugsin) with `mesosphere/jenkins:2.1.0-2.19.3`  Thanks for your dedication to this issue.

**Comment by LinkMJB** [comment] 2017-01-03 16:16
If Mesosphere merges my PR (https://github.com/mesosphere/dcos-jenkins-service/pull/118/files) it will be on its way to getting fixed (Mesosphere will still need to build the Jenkins Docker image, and update the Jenkins DC/OS package afterward). For now, you can easily workaround it by manually building the Dockerfile in my PR, and use that as your Docker image instead.

**Comment by ssk2** [comment] 2017-01-05 03:04
Hello all, apologies for the silence! We've been investigating approaches for our Jenkins container that allow users to upgrade plugins as requested here and retain our ability to bundle a known good set of plugins with the service.

We failed to mention earlier that one of the hard requirements for this package is that it must include a minimum set of known good plugins. This is desirable for a subset of DC/OS users who manage hundreds of Jenkins instances and want each installation to provide an immutable, baseline, set of plugins. They will then extend this base image to provide their own additional plugins. (As you all probably well know, Jenkins plugins are notorious for often breaking Jenkins from version to version.)  

This approach worked well enough for us until the `2.x.x` version of Jenkins, at which point Jenkins' behaviour with respect to bundled plugins changed - making it impossible to upgrade plugins (as you've all found). Unfortunately, whilst @LinkMJB's pull request fixes the plugin upgrade behaviour, using the official Jenkins war (instead of the one we compile) removes the our bundled set of plugins - so we can't use that approach. 

@colin-msphere has been investigating using the official Jenkins Docker image (see #122). So far, in his tests, this works as intended and allows upgrades of plugins and Jenkins itself. Note that if you restart the container, the Jenkins war file will get overwritten (since this is persisted within the container) but any upgraded plugins will be retained. 

I'm going to try and take this through to the finish line this week, but if you feel like trying it out, simply replace the Docker image for the Jenkins service with `mesosphere/jenkins-dev:use-jenkins-docker`.

Apologies again for the delay in getting this resolved!

**Comment by colin-msphere** [comment] 2017-02-13 18:26
The latest release addresses this issue and allows upgrading of plugins and retaining those upgrades upon restart.

**Comment by colin-msphere** [comment] 2017-02-28 16:09
No additional comments have been added in two weeks. Closing this issue.

**Closed by colin-msphere** 2017-02-28 16:09 UTC
